### PR TITLE
Add assertions and logging to unmatch command [WIP]

### LINKED ISSUE #142: [Alek] `screen job` feedback does not match the filtered list
to replicate this 
- `match 1 2`
- `view company 2`
- `screen job 1`

`screen job 1` a second will return `2 candidates found`

image

### LINKED ISSUE #170: [Alek] `unmatch` logic does not work
Screenshot 2024-10-30 at 11 22 50 PM

assertion has failed as hasJobMatchedContact is false when it should be true

### PR DESCRIPTION
**Pull request by AlekKwek18**
- fixes #142 
- fixes #170

### CODE REVIEW

**Review by KengHian — CHANGES_REQUESTED** [review]
Seems that this PR is for logging, where did you remove the bidirectional association?

From these changes, it is not clear to me that the bugs have been fixed, have you verified it yourself?

**Comment by Green-Tea-123** [comment]
I'm not sure where the bidirectional association is being removed, perhaps you could comment?

**Comment by AlekKwek18** [comment]
After further investigation, I realized that @Quasant  had already removed the bidirectional association in a previous update. It seems there was an issue syncing his changes with my branch, which led to them not reflecting in my code. As a result, I mistakenly removed the bidirectional code again. I have now corrected this and ensured the latest changes are fully in sync.

**Review by KengHian — APPROVED** [review]
Understood, the code seems good to me, just ensure that the bugs are indeed fixed by these changes before merging

**Review by Green-Tea-123 — APPROVED** [review]
LGTM

**Pull request merged**
